/**
 * `cn` is the shadcn/Spartan className helper: clsx + tailwind-merge.
 *
 * The canonical implementation ships as `hlm` (generated by the Spartan CLI in
 * `./hlm`); `cn` is kept as the familiar alias used across the codebase.
 */
export { hlm as cn } from './hlm';
